version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: SomePassw0rd
      POSTGRES_DB: testtask
      PG_DATA: /var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
    networks:
      - testtask
  testapi:
    env_file:
      - ./.env
    links:
        - postgres:postgres
    volumes:
      - .:/usr/src/app
    build:
      context: .
      target: development
    environment:
      DATABASE_URL: postgresql://postgres:SomePassw0rd@postgres:5432/testtask
    command: yarn start:dev
    ports:
      - "80:3000"
    depends_on:
      - postgres
    networks:
      - testtask
networks:
  testtask:
